name: 'hitokoto' # 服务名称，例如：hitokoto
url: 'https://v1.hitokoto.cn' # 服务地址，例如：https://v1.hitokoto.cn
api_name: 'demo_prprpr' # 服务标识，取个好区分的标识吧，例如：cd-01-demo
server: # 配置 HTTP 服务的信息
  host: 127.0.0.1 # 监听的地址
  port: 8000 # 监听的端口
  compress_body: true # 是否使用 GZIP 压缩
redis: # 配置 Redis
  host: 127.0.0.1 # Redis 主机名
  port: 6379 # Redis 端口
  password: '' # Redis 密码
  database: 0 # Redis 数据库
sentences_ab_switcher: # 本节是服务 AB 异步更新的配置，如果您不知道这个是什么意思，请保持默认
  a: 1 # a 状态对应的 redis 数据库
  b: 2 # b 状态对应的 redis 数据库
remote_sentences_url: https://cdn.jsdelivr.net/gh/hitokoto-osc/sentences-bundle@latest/ # 语句库地址，通常默认即可。如果您想使用您自己打包部署的语句库，您可以修改此项
workers: 0 # 启动 Worker 数目。0 表示启动和 CPU 核心数相同数量的 Worker
extensions: # 控制扩展
  netease: true # 网易云音乐接口
requests:
  enabled: true # 是否启用请求数目统计
  hosts: # 需要单独统计的主机名
    - v1.hitokoto.cn
    - international.v1.hitokoto.cn
    - api.a632079.me
    - api.hitokoto.cn
    - sslapi.hitokoto.cn
telemetry: # 遥测服务
  performance: true # 性能监控
  error: true # 错误报告
  usage: true # 使用报告
  debug: false # 是否启用调试模式（该模式会让遥测服务打印调试信息）
